### ISSUE TITLE
Should compositeKey be in a module

### ISSUE THREAD

**Issue by bmeck** [tc39/proposal-collection-normalization#3]
It seems weird to have it hang off of all the existing globals.

**Comment by bmeck** [comment]
@zloirock at stage 1? IDK, API is still very unstable and the use case is still being looked into. You could make it a global for testing purposes, but I wouldn't ask people to ship this specific API anytime soon since it likely will have changes.

**Comment by bmeck** [comment]
@ljharb I consider an initial spec text to be doable without directly defining the location. Similar to how `global` does not revert stages when finding the proper location it should live on.

**Comment by ljharb** [comment]
It’s not clear that we will ever be able to omit creating new globals, even with builtin modules, nor is it clear builtin modules are even viable. If a proposal lacks a concrete non-module location, then i don’t think it can advance to stage 2, since we shouldn’t be committing to putting a feature in the language if its foundation lacks the same commitment.

**Comment by bmeck** [comment]
this issue is a holdover from when this proposal had more features, the more minimal collection normalization proposal doesn't have this. closing.
